### ISSUE TITLE
Update images after new releases 

### ISSUE THREAD

**Issue by traversaro** [robotology-playground/docker_images#2]
cc @diegoferigo

**Comment by diegoferigo** [comment]
[This commit](https://github.com/robotology-playground/docker_images/commit/fe5f161f642025ad7e92fc533aac142ab5d3df3e) should fix the status of the images that use RTF on top of `yarp:master`.

**Comment by diegoferigo** [comment]
Closing, let me know if you encounter again issues due to the recent YARP release.
